<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT_CURA_LOGIN_Validation_TestSuite_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3c35200b-f5d9-4f6a-8118-edaa13a89554</testSuiteGuid>
   <testCaseLink>
      <guid>47065bd6-6a33-42f9-949f-ef7995648002</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data-Driven Testing/TC_CHS_LOING_Excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>92318691-7ad1-40a3-802e-4849ab420f1d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CURA_LOGIN_TestData/CURU_LOGIN_TestData_Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>92318691-7ad1-40a3-802e-4849ab420f1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>7e713b5d-bfa1-413a-b432-48ac454da7e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>92318691-7ad1-40a3-802e-4849ab420f1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b38580fd-adae-42e4-a33e-a9ab45b088ec</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
